authapp/urls.py
from django.urls import path

from .views import RegisterView, LoginView, LogoutView

app_name = 'authapp'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
]

financemanager/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    dashboard,
    TransactionCreate,
    History,
    TransactionViewset,
    get_categories_by_type,
)


app_name = 'finance'

router = DefaultRouter()
router.register('transactions', TransactionViewset)

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('create/', TransactionCreate.as_view(), name='create-trans'),
    path('history/', History.as_view(), name='history'),
    path('get_categories/', get_categories_by_type, name='get-categories'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

overrideuser/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)

from .views import index

urlpatterns = [
    path('', index, name='main'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('finance/', include('financemanager.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

financemanager/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone


class Type(models.TextChoices):
    INCOME = "INCOME", "Income"
    OUTCOME = "OUTCOME", "Outcome"


class Category(models.Model):
    name = models.CharField(
        'Name',
        max_length=50
    )

    type = models.CharField(
        "Type",
        max_length=20,
        choices=Type.choices,
        default=Type.OUTCOME
    )

    def __str__(self):
        return self.name


class Transaction(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    type = models.CharField(
        "Type",
        max_length=20,
        choices=Type.choices,
        default=Type.OUTCOME
    )

    amount = models.DecimalField(
        max_digits=16,
        decimal_places=2
    )

    date = models.DateField(
        default=timezone.now
    )

    description = models.TextField(
        max_length=255,
        null=True,
        blank=True
    )

    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    def clean(self):
        if self.category and self.category.type != self.type:
            raise ValidationError(
                f"Category '{self.category.name}' does not match Transaction "
                f"type '{self.type}'"
            )

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

financemanager/forms.py
from django import forms
from django.utils import timezone

from .models import Transaction, Category


class TransactionCreateForm(forms.ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'value': timezone.now().date()
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['category'].initial =
        self.initial['category'] = Category.objects.filter(type="OUTCOME")

    def save(self, commit=True):
        trans = super().save(commit=False)
        if commit:
            trans.save()
        return trans

    class Meta:
        model = Transaction
        fields = ('category', 'date', 'type', 'amount', 'description')

financemanager/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from rest_framework import permissions, viewsets, filters
from rest_framework.response import Response

from .forms import TransactionCreateForm
from .models import Transaction, Category
from .serializers import TransactionSerializer


@login_required
def dashboard(request):
    return render(request, 'financemanager/dashboard.html')


def get_categories_by_type(request):
    transaction_type = request.GET.get('type')
    categories = Category.objects.filter(type=transaction_type)
    return render(
        request,
        'financemanager/category_dropdown.html',
        {'categories': categories}
    )


class TransactionCreate(LoginRequiredMixin, CreateView):
    form_class = TransactionCreateForm
    template_name = 'financemanager/createtransaction.html'
    success_url = reverse_lazy('finance:dashboard')

    def form_valid(self, form):
        trans = form.save(commit=False)
        trans.user = self.request.user
        return super().form_valid(form)


class History(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'financemanager/history.html'
    context_object_name = 'transactions'


class TransactionViewset(viewsets.ModelViewSet):
    http_method_names = ['get']
    queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        return Transaction.objects.filter(user=user).order_by('-id')

    class Meta:
        ordering = ['-id']

financemanager/templates/financemanager/category_dropdown.html
{% for category in categories %}
    <option value="{{ category.id }}">{{ category.name }}</option>
{% endfor %}

financemanager/templates/financemanager/createtransaction.html
{% extends 'base.html' %}

{% block title %}
	New transaction
{% endblock %}

{% block body %}

	<form action="" method="POST">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        <label for="id_type">Type</label>
        <select name="type" id="id_type" hx-trigger="load, click" hx-get="{% url 'finance:get-categories' %}" hx-target="#id_category">
            <option value="OUTCOME">Outcome</option>
            <option value="INCOME">Income</option>
        </select>
        <label for="id_category">Category</label>
        <select name="category" id="id_category">

        </select>
        {{ form.date }}
        {{ form.amount }}
        {{ form.description }}
        <input type="submit">
    </form>

{% endblock %}

financemanager/templates/financemanager/dashboard.html
{% extends 'base.html' %}

{% block title %}
	Dashboard
{% endblock %}

{% block body %}

    Dashboard

    <div style="width:45%">
        <canvas id="chart1"></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        const ctx = document.getElementById('chart1');

        new Chart(ctx, {
            type: 'radar',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>

{% endblock %}

financemanager/templates/financemanager/history.html
{% extends 'base.html' %}

{% block title %}
	Dashboard
{% endblock %}

{% block body %}

    <ul>
    {% for transaction in transactions %}
    	<li>{{ transaction.category }}, {{ transaction.amount }} {{ user.currency.symbol }}</li>
    {% endfor %}

    </ul>

{% endblock %}