authapp/urls.py
from django.urls import path

from .views import RegisterView, LoginView, LogoutView

app_name = 'authapp'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
]

financemanager/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    dashboard,
    TransactionCreate,
    History,
    TransactionViewset,
    get_categories_by_type,
)


app_name = 'finance'

router = DefaultRouter()
router.register('transactions', TransactionViewset)

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('create/', TransactionCreate.as_view(), name='create-trans'),
    path('history/', History.as_view(), name='history'),
    path('get_categories/', get_categories_by_type, name='get-categories'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

overrideuser/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)

from .views import index

urlpatterns = [
    path('', index, name='main'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('finance/', include('financemanager.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
    	    Base
        {% endblock %}
    </title>
</head>
<body>

    <header style="border-bottom: 1px black solid; flex-direction: row">
        Finance manager
        {% if user.is_authenticated %}
            <a href="{% url 'finance:dashboard' %}">Dashboard</a>
            <a href="{% url 'finance:create-trans' %}">New transaction</a>
            <a href="">History</a>
            <a href="">Statistics</a>
            
            Hello, {% firstof user.firstname user.email %}!

            <form action="{% url 'authapp:logout' %}" method="POST">
                {% csrf_token %}
                <button>Logout</button>
            </form>
        {% else %}
            <a href="{% url 'authapp:login' %}">LogIn</a>
        {% endif %}
    </header>


    {% block body %}

    {% endblock %}

    <script src="https://unpkg.com/htmx.org"></script>

</body>
</html>